---
# handlers file for cis-security

# The auditd service has to be restarted with the actual SYS5 service
# command rather than the service module (which uses systemd)
# https://access.redhat.com/solutions/2664811
- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
    use: service
  when: ansible_os_family != "windows"
  listen: "restart auditd"

# reboot a machine. Give it 10 minutes to come up in case it
#  needs to do a selinux relabel
- name: reboot
  reboot:
    reboot_timeout: 600

- name: restart ntpd
  ansible.builtin.service:
    name: ntpd
    state: restarted

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: start iptables
  ansible.builtin.service:
    name: iptables
    state: started

- name: restart tmpfs
  ansible.builtin.systemd:
    name: tmp.mount
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

# Call the grub config file rebuilding program
# There is no grub module, so we have to do it with shell
- name: rebuild grub
  ansible.builtin.command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg

# Call the grub config file rebuilding program on ubuntu
# There is no grub module, so we have to do it with shell
- name: rebuild ubuntu-grub
  ansible.builtin.command: /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg

- name: update crypto_policy
  ansible.builtin.command: /usr/bin/update-crypto-policies

- name: restart aidecheck
  ansible.builtin.systemd:
    name: aidecheck
    enabled: yes
    state: restarted

- name: flush network routes
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: "1"
    reload: yes
    state: present
    sysctl_set: yes
  loop:
    - net.ipv4.route.flush
    - net.ipv6.route.flush

- name: restart timesyncd
  ansible.builtin.systemd:
    name: systemd.timesyncd
    enabled: yes
    state: restarted

- name: restart ufw
  community.general.ufw:
    state: enabled
